
name: Java CI with Maven #workflow name

on:
  push:
    branches: [ "master" ] #when someone push to this branch will trigger this workflow
  pull_request:
    branches: [ "master" ] #when someone pull to this branch will trigger this workflow

jobs: #groups set of actions that will be executed.
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 #will checkout the repository in github first
    - name: Set up JDK 11 
      uses: actions/setup-java@v3 #prepares the environment with java 
      with:
        java-version: '11' #java version used in this project.
        distribution: 'temurin'
        cache: maven
    - name: test with Maven
      run: mvn -B test --file pom.xml #will test this command in maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml #will run this command in maven
    - name: docker login
      run:
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the docker Image
      run: docker build . --file Dockerfile --tag lewiscontato99/mvc-testing
    - name: Docker push to DockerHub
      run: docker push lewiscontato99/mvc-testing

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    
