
name: Java CI with Maven #workflow name

on:
  push:
    branches: [ "master" ] #when someone push to this branch will trigger this workflow
  pull_request:
    branches: [ "master" ] #when someone pull to this branch will trigger this workflow

jobs: #groups set of actions that will be executed.
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11 
      uses: actions/checkout@v3 #will checkout the repository in github first
      with:
          java-version: '11' #java version used in this project.
          distribution: 'temurin'
          cache: maven  
        
